### ISSUE TITLE
Included addAuthToken method in consumer module

### ISSUE THREAD

**Issue by sreenicibc** [networknt/light-consumer-4j#12]
(Jira-API 4)Included the addAuthToken method in consumer module, This will help users in setting the subject token on the request.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Included addAuthToken method in consumer module](https://trello.com/c/Naqpt61K/92-included-addauthtoken-method-in-consumer-module)
