### ISSUE TITLE
environment/tag become mandatory by using light-comsumer-4j

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-consumer-4j#20]
Based the code, if the service api didn't set environment, system throw exception:

            if (env != null && env.length() > 0) {
                serviceDef.setEnvironment(env);
            } else {
                throw new RuntimeException("Service \"" + serviceDef.getServiceId() + "\" was not configured with an environment.");
            }

But actually, based on server.yml, the environment should be optional;
-- environment tag that will be registered on consul to support multiple instances per env for testing.
-- https://github.com/networknt/light-doc/blob/master/docs/content/design/env-segregation.md
--  This tag should only be set for testing env, not production. The production certification process will enforce it.
-- environment: dev1

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [environment/tag become mandatory by using light-comsumer-4j](https://trello.com/c/Z6oJKUde/91-environment-tag-become-mandatory-by-using-light-comsumer-4j)
