### ISSUE TITLE
Create new consumer side parallel client to use new features in light-4j client module

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-consumer-4j#30]
1. Wrap consumer method for http2Client.callService for better usage.

2. Add more test cases for performance and stress test

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create new consumer side parallel client to use new features in light-4j client module](https://trello.com/c/nMTNnWvm/180-create-new-consumer-side-parallel-client-to-use-new-features-in-light-4j-client-module)
