### ISSUE TITLE
add one more method into LightRestClient for http get with request header map

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-consumer-4j#33]
add one more method into LightRestClient for http get with request header map.

    <T> T get(ServiceDef serviceDef, String path, Class<T> responseType, Map<String, ?> headerMap) throws RestClientException;

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add one more method into LightRestClient for http get with request header map](https://trello.com/c/f99Hyqur/193-add-one-more-method-into-lightrestclient-for-http-get-with-request-header-map)
