### ISSUE TITLE
1.6.x version json-schema-validator version confilct

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-consumer-4j#39]
in the 1.6.x the json-schema-validator version is too old:

       <version.json-schema-validator>1.0.3</version.json-schema-validator>

When we introduce the light-consumer-4j to the project, it cause the validator version conflict

**Comment by stevehu** [comment]
light-consumer-4j in 1.6.x branch is not synched with the latest dependencies and that is why the version-upgrade is not working on the branch.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1.6.x version json-schema-validator version confilct](https://trello.com/c/eevsWfe0/348-16x-version-json-schema-validator-version-confilct)
