### ISSUE TITLE
Parked Connections Default Time setting

### ISSUE THREAD

**Issue by SureshTak** [networknt/light-consumer-4j#48]
Hi Steve, 

 Is there any way that we can pass ttlParkedValue from configuration file(Client.yml). Below consutrctor setting ttlParked to 1 min by default and there is no way that Client can manage this setting to differnt value. 

Our project is on JDK 1.8 and we currently planning to update  ligh4j consumer version to  (1.6 x) .

Is there any plan to provide support to  read below default value from Configuration file?

```
public CacheableConnection(ClientConnection clientConnection, long ttl, int maxReqCount) {
        this.ttlParked = 60000L;
        this.maxReqCount = -1;
        this.clientConnection = clientConnection;
        this.ttl = ttl;
        this.lifeStartTime = System.currentTimeMillis();
        this.maxReqCount = maxReqCount;
    }
```

**Comment by stevehu** [comment]
@stakReal Yes. We can definitely make it configurable. The value is to control how long the connection will be reside in the parked pool before it is finally closed. If we close the connection immediately, other threads that are using the same connection might throw an error and inflight requests will fail. This only happens for HTTP/2 as one connection can be shared between multiple threads. The default value is 60 seconds hardcoded and it should be sufficient enough as most of our requests will be completed in less than 1 second. What is your use case? Are you planning to set it more than 60 seconds? or less?

**Comment by stakReal** [comment]
Hi Steve,  Yes we are using H2 and  have requirement to configure more than 60 seconds. Client wants us to configure 2 mins..
Can you provide some info like how I can make it configurable with version (1.6x)?

**Comment by stevehu** [comment]
Got it. It should be easy to put this parameter into the client.yml and add a properties to the config. Would you be able to submit a PR? Thanks.

**Comment by stakReal** [comment]
Sure, Should I do changes on 1.6x branch and then submit PR?  From requirement perspective, if I understood correct, we should access newly added config parameter inside default constructor and set to ttlParked property correct?
I see there is another constructor in the same which has ttlParked as parameter.Is this constructor is not in use?

**Comment by stevehu** [comment]
You can use the 1.6.x branch and I will try to cherry-pick it to the master branch. I think you just need to update the ClientConfig class after adding one more properties to the cleint.yml file.

**Comment by stakReal** [comment]
I looked at the light4j code and it seems that, I would need to change multiple files in order to read it from Client yaml and pass it cachableConnection class. 

**HTTPClientRequest:**. - new property. to read it from client yaml.

```
private long ttlParked;

    public long getTtlParked() {
        return ttlParked;
    }

    public void setTtlParked(long ttlParked) {
        this.ttlParked = ttlParked;
    }
```

**HTTPClientBuilder:**  -  ttlParked argument to below connectionCacheManager.getConnection()

```
ClientConnection clientConnection = connectionCacheManager.getConnection(requestHost,
                httpClientRequest.getConnectionCacheTTLms(), httpClientRequest.getConnectionRequestTimeout(),
                httpClientRequest.getHttp2Enabled(),httpClientRequest.getMaxReqCount(),**httpClientRequest.getTtlParked())**;
```

and change connectionCacheManager.getConnection to use below constructor  of CacheableConnection.

```
public CacheableConnection(ClientConnection clientConnection, long ttl, int maxReqCount, long ttlParked) {
        this(clientConnection, ttl, maxReqCount);
        this.ttlParked = ttlParked;
    }
```

Please let me know if you are ok with the changes.

**Comment by SureshTak** [comment]
Hi Steve, Can you confirm if I can submit pull request with above changes?

**Comment by stevehu** [comment]
@SureshTak Yes. Please submit a PR and I will perform a test. Thanks a lot for your help.

**Comment by SureshTak** [comment]
@stevehu , Please review and merge the pull request.

**Comment by stevehu** [comment]
It looks good to me. The only concern I have is the signature change might break existing applications. I am wondering if you could keep the existing signature for the getConnection and add a new one with the parkedConnectionTTL. With this case, we can keep the test cases intact. For users who want to use the parked TTL, they can use the new method added, for existing users, they will use the default value. What do you think?

**Comment by SureshTak** [comment]
@Steve, getConnection method is internal to light4j , Clients will be invoking HTTPClientBuilder.send() method, which will internally invoke getConnection method. I don't see use case where clients directly using getConnection.

**Comment by stevehu** [comment]
@chenyan71 Could you please review this PR? I am wondering if the method signature change will break your application. Thanks.

**Comment by stevehu** [comment]
@SureshTak I agree with you that most users will call the send method from the builder. However, the getConnection is a public method and some users might call it directly to get a connection for their application without using the builder. We cannot predict or limit how users will use the module and I have seen so many creative ways from our users.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parked Connections Default Time setting light-consumer-4j 1.6.x](https://trello.com/c/DmrIaeLw/781-parked-connections-default-time-setting-light-consumer-4j-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parked Connections Default Time setting light-consumer-4j master](https://trello.com/c/Bc7YwJeD/782-parked-connections-default-time-setting-light-consumer-4j-master)
