### ISSUE TITLE
Expose discovered server url in the builder class

### ISSUE THREAD

**Issue by zabooma** [networknt/light-consumer-4j#9]
Clients can use getServiceUrl() method to see what is the actual discovered / load balanced URL of the server before they issue a call to the service. Use case for this is to be able to log the actual server URL in the client's log.

**Comment by NicholasAzar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Expose discovered server url in the builder class of consumer module](https://trello.com/c/RN62bvgs/25-expose-discovered-server-url-in-the-builder-class-of-consumer-module)
